name: Build & Push Images

on:
  push:
    branches: [production]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Backend
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/fullstack-backend:latest ./packages/backend
          docker push ghcr.io/${{ github.repository_owner }}/fullstack-backend:latest

      - name: Build Frontend
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/fullstack-frontend:latest ./packages/frontend
          docker push ghcr.io/${{ github.repository_owner }}/fullstack-frontend:latest